version: "3"
services:
  app:
    image: node-api-motorbikeonline
    container_name: motorbikeonline
    build: ./
    restart: always
    ports:
    - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080